const ACTIONS = {
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    GET_ADMIN_TOKEN: 'GET_ADMIN_TOKEN',
    GET_ADMIN: 'GET_ADMIN',

    PARENT_LOGIN: 'PARENT_LOGIN',
    GET_PARENT_TOKEN: 'GET_PARENT_TOKEN',
    GET_PARENT: 'GET_PARENT',
    GET_CHILD: 'GET_CHILD',

    TEACHER_LOGIN: 'TEACHER_LOGIN',
    GET_TEACHER_TOKEN: 'GET_TEACHER_TOKEN',
    GET_TEACHER: 'GET_TEACHER',

    STUDENT_LOGIN: 'STUDENT_LOGIN',
    GET_STUDENT_TOKEN: 'GET_STUDENT_TOKEN',
    GET_STUDENT: 'GET_STUDENT',

    GET_ALL_PARENTS: 'GET_ALL_PARENTS',
    GET_ALL_TEACHERS: 'GET_ALL_TEACHERS',
    GET_ALL_STUDENTS: 'GET_ALL_STUDENTS',

    GRADES: 'GRADES',
    HEADINGS: 'HEADINGS',
    CHAPTERS: 'CHAPTERS',
    TOPICS: 'TOPICS',

    TEAMS: 'TEAMS',

    SCHEDULES: 'SCHEDULES'
}

export default ACTIONS